### ISSUE TITLE
Inplace problem caused by Leaky neurons using snntorch

### ISSUE THREAD

**Issue by yimengshan1** [jeshraghian/snntorch#197]
* snntorch version:0.53
* Python version:3.9
* Operating System:ubuntu18.04

### Description

I repeated the experiment of a paper. I can confirm that there is no problem with the network, but I will have an inplace error when I carry out backpropagation, and I do not carry out the inplace operation. This problem often occurs. In the past, I used to add utils. reset (net) to solve it, but this time it has no effect

### What I Did

all of my code in here.
```python
# 目前已经可以使用class进行模块组合和forward了
import torch.nn.functional as F
import torch, torch.nn as nn
import snntorch as snn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from snntorch import surrogate
from snntorch import utils
import snntorch.functional as SF
from snntorch import backprop
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter('./runs')
torch.autograd.set_detect_anomaly(True)

device = torch.device("cuda:0")
data_path='../data'
batch_size = 8
num_epochs = 1
num_steps = 25

transform = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.Grayscale(),
    transforms.ToTensor(),
    transforms.Normalize((0,),(1,))])
mnist_train = datasets.MNIST(data_path, train=True, download=True, transform=transform)
mnist_test = datasets.MNIST(data_path, train=False, download=True, transform=transform)

train_loader = DataLoader(mnist_train, batch_size, shuffle=True)
test_loader = DataLoader(mnist_test, batch_size, shuffle=True)




class GlobalAvgPool2d(nn.Module):           # 全局平均池化
    def __init__(self):
        super(GlobalAvgPool2d, self).__init__()
    def forward(self, x):
        a = nn.AvgPool2d(kernel_size=x.shape[2:])
        return a(x)

class coding(nn.Module):            # 自适应编码层
    def __init__(self, in_channels, out_channels, stride, padding, kernels, pooling_kernel, beta, spike_grad):
        super().__init__()
        self.conv3x3 = nn.Conv2d(in_channels, out_channels, kernels, stride=stride, padding=padding)
        self.leaky = snn.Leaky(beta=beta, spike_grad=spike_grad, init_hidden=True, learn_beta=True, learn_threshold=True)
        self.pooling = nn.MaxPool2d(pooling_kernel)

    def forward(self, x):
        result = self.pooling(self.leaky(self.conv3x3(x)))
        return result


def coding_made(in_channels, out_channels, stride, padding, kernels, pooling_kernel=2, beta=0.9, spike_grad=surrogate.atan()):
    blk = []
    blk.append(coding(in_channels, out_channels, stride, padding, kernels, pooling_kernel, beta, spike_grad))
    return nn.Sequential(*blk)


class block(nn.Module):             # 脉冲稠密块
    def __init__(self, in_channels, out_channels, stride, padding, kernels, beta, spike_grad):
        super().__init__()
        self.bn1 = nn.BatchNorm2d(in_channels[0])
        self.leaky1 = snn.Leaky(beta=beta[0], spike_grad=spike_grad[0], init_hidden=True, learn_beta=True, learn_threshold=True)
        self.conv1x1 = nn.Conv2d(in_channels[0], out_channels[0], kernel_size=kernels[0], stride=stride[0], padding=padding[0])
        self.bn2 = nn.BatchNorm2d(out_channels[0])
        self.leaky2 = snn.Leaky(beta=beta[1], spike_grad=spike_grad[1], init_hidden=True, learn_beta=True, learn_threshold=True)
        self.conv3x3 = nn.Conv2d(in_channels[1], out_channels[1], kernel_size=kernels[1], stride=stride[1], padding=padding[1])


    def forward(self, x):
        result = self.conv3x3(self.leaky2(self.bn2(self.conv1x1(self.leaky1(self.bn1(x))))))
        results = torch.cat([x, result], dim=1)
        return result

# 初始化模块
def block_made(in_channels, out_channels, stride, padding, kernels, beta=[0.9, 0.9], spike_grad=[surrogate.atan(), surrogate.atan()]):
    blk = []
    blk.append(block(in_channels, out_channels, stride, padding, kernels, beta, spike_grad))
    return nn.Sequential(*blk)

class spiking_transform(nn.Module):             # 脉冲转换块
    def __init__(self, in_channels, out_channels, stride, padding, kernels, pooling_kernel, beta, spike_grad):
        super().__init__()
        self.bn = nn.BatchNorm2d(in_channels)
        self.leaky = snn.Leaky(beta=beta, spike_grad=spike_grad, init_hidden=True, learn_beta=True, learn_threshold=True)
        self.conv1x1 = nn.Conv2d(in_channels, out_channels, kernels, stride=stride, padding=padding)
        self.pooling = nn.AvgPool2d(pooling_kernel)

    def forward(self, x):
        result = self.pooling(self.conv1x1(self.leaky(self.bn(x))))
        return result

def spiling_transform_made(in_channels, out_channels, stride, padding, kernels, pooling_kernel=2, beta=0.9, spike_grad=surrogate.atan()):
    blk = []
    blk.append(spiking_transform(in_channels, out_channels, stride, padding, kernels, pooling_kernel, beta, spike_grad))
    return nn.Sequential(*blk)

class all_connection(nn.Module):             # 决策层
    def __init__(self, linear_in, linear_out, beta, spike_grad):
        super().__init__()
        self.Globalavgpool = GlobalAvgPool2d()
        self.linear = nn.Linear(linear_in, linear_out)
        self.leaky = snn.Leaky(beta=beta, spike_grad=spike_grad, init_hidden=True, learn_beta=True, learn_threshold=True)

    def forward(self, x):
        flatten_result = torch.flatten((self.Globalavgpool(x)), start_dim=1, end_dim=3)     # 拉平第一个维度到第三个维度（通道+w+h）
        result = self.leaky(self.linear(flatten_result))
        return result

def all_connection_made(linear_in, linear_out, beta=0.9, spike_grad=surrogate.atan()):
    blk = []
    blk.append(all_connection(linear_in, linear_out, beta, spike_grad))
    return nn.Sequential(*blk)

net = nn.Sequential()
net.add_module("coding", coding_made(1, 128, 1, 1, 3, 2))
net.add_module("block1", block_made([128, 32], [32, 136], [1, 1], [0, 1], [1, 3]))
net.add_module("block2", block_made([136, 32], [32, 144], [1, 1], [0, 1], [1, 3]))
net.add_module("block3", block_made([144, 32], [32, 152], [1, 1], [0, 1], [1, 3]))
net.add_module("block4", block_made([152, 32], [32, 160], [1, 1], [0, 1], [1, 3]))
net.add_module("block5", block_made([160, 32], [32, 168], [1, 1], [0, 1], [1, 3]))
net.add_module('transform', spiling_transform_made(168, 84, 1, 0, 1, 2))
net.add_module("connection", all_connection_made(84, 10))
utils.reset(net)
net.cuda()
# print(net)
# print(net(torch.rand(128, 1, 64, 64, device='cuda:0')).shape)

optimizer = torch.optim.Adam(net.parameters(), lr=2e-3, betas=(0.9, 0.999))
loss_fn = SF.mse_count_loss(correct_rate=0.8, incorrect_rate=0.2)

loss_hist = []      # 记录损失
acc_hist = []       # 记录迭代精度

def net_do(data):
    # utils.reset(net)
    mem_rec = []
    for i in range(num_steps):
        mem = net(data)
        mem_rec.append(mem)
    return torch.stack(mem_rec)

for epoch in range(num_epochs):
    for i, (data, targets) in enumerate(iter(train_loader)):
        data = data.to(device)
        targets = targets.to(device)
        net.train()         # 进入训练模式，参数会随着迭代而改变
        result = net_do(data)              # spk_rec的格式为：[num_steps, batch_size, 类别数]
        loss_val = loss_fn(result, targets)
        optimizer.zero_grad()
        loss_val.backward(retain_graph=True)
        optimizer.step()
        loss_hist.append(loss_val.item())

        # 每25组数据输出一次
        if i % 25 == 0:
          net.eval()
          print(f"Epoch {epoch}, 第 {i} 次循环 \n训练损失: {loss_val.item():.2f}")
          acc = SF.accuracy_rate(result, targets)          # 使用峰值计数来衡量准确率
          acc_hist.append(acc)
          print(f"Accuracy: {acc * 100:.2f}%\n")

# 对整个测试集进行测试
def test_accuracy(data_loader, num_steps):
  with torch.no_grad():
    total = 0
    acc = 0
    net.eval()
    for data, targets in iter(data_loader):
      data = data.to(device)
      targets = targets.to(device)
      result = net_do(data)       # spk_rec的格式为：[num_steps, batch_size, 类别数]
      acc += SF.accuracy_rate(result, targets) * result.size(1)           # 准确率 * 本批次的数据总量
      total += result.size(1)

  return acc/total


print(f"在整个测试集上的准确率为: {test_accuracy(test_loader, num_steps)*100:.3f}%")
```

------------------------------------------------------------------------------------------------------------------------------------------
when I run the code,The error is as follows：

/home/sym/anaconda3/envs/snn_1/bin/python3.9 /home/sym/PycharmProjects/spiking-classify/基于脉冲神经网络的钢材表面缺陷识别研究.py 
Epoch 0, 第 0 次循环 
训练损失: 0.00
Accuracy: 0.00%

/home/sym/anaconda3/envs/snn_1/lib/python3.9/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in AddmmBackward0. Traceback of forward call that caused the error:
  File "/home/sym/PycharmProjects/spiking-classify/基于脉冲神经网络的钢材表面缺陷识别研究.py", line 169, in <module>
    result = net_do(data)              # spk_rec的格式为：[num_steps, batch_size, 类别数]
  File "/home/sym/PycharmProjects/spiking-classify/基于脉冲神经网络的钢材表面缺陷识别研究.py", line 148, in net_do
    mem = net(data)
  File "/home/sym/anaconda3/envs/snn_1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sym/PycharmProjects/spiking-classify/基于脉冲神经网络的钢材表面缺陷识别研究.py", line 139, in forward
    result = self.connection(transform_result)
  File "/home/sym/anaconda3/envs/snn_1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sym/anaconda3/envs/snn_1/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/sym/anaconda3/envs/snn_1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sym/PycharmProjects/spiking-classify/基于脉冲神经网络的钢材表面缺陷识别研究.py", line 104, in forward
    result = self.leaky(self.linear(flatten_result))
  File "/home/sym/anaconda3/envs/snn_1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sym/anaconda3/envs/snn_1/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484806139/work/torch/csrc/autograd/python_anomaly_mode.cpp:102.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/home/sym/PycharmProjects/spiking-classify/基于脉冲神经网络的钢材表面缺陷识别研究.py", line 172, in <module>
    loss_val.backward(retain_graph=True)
  File "/home/sym/anaconda3/envs/snn_1/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/sym/anaconda3/envs/snn_1/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [84, 10]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

Process finished with exit code 1

-----------------------------------------------------------------------------------------------------------------------------------------------

I hope someone can help me

**Comment by ridgerchu** [comment]
Hello,
It seems that you just call util.reset(net) just once, but it needs to be call in each feed forward process. Have you tried to put this in the beginning of the training code? Like this:
```python
for epoch in range(num_epochs):
    for i, (data, targets) in enumerate(iter(train_loader)):
        utils.reset_net(net) # reset in each training process.
        data = data.to(device)
        targets = targets.to(device)
        net.train()         # 进入训练模式，参数会随着迭代而改变
        result = net_do(data)              # spk_rec的格式为：[num_steps, batch_size, 类别数]
        loss_val = loss_fn(result, targets)
        optimizer.zero_grad()
        loss_val.backward(retain_graph=True)
        optimizer.step()
        loss_hist.append(loss_val.item())

        # 每25组数据输出一次
        if i % 25 == 0:
          net.eval()
          print(f"Epoch {epoch}, 第 {i} 次循环 \n训练损失: {loss_val.item():.2f}")
          acc = SF.accuracy_rate(result, targets)          # 使用峰值计数来衡量准确率
          acc_hist.append(acc)
          print(f"Accuracy: {acc * 100:.2f}%\n")
```

**Comment by yimengshan1** [comment]
Thank you for your kind help
I have tried to do this, but it has no effect on the result. It will still report the same error
I tried to change the code of the training part to the following
```
def net_do(data):
    utils.reset(net)
    mem_rec = []
    for i in range(num_steps):
        mem = net(data)
        mem_rec.append(mem)
    return torch.stack(mem_rec)


for epoch in range(num_epochs):
    for i, (data, targets) in enumerate(iter(train_loader)):
        data = data.to(device)
        targets = targets.to(device)
        net.train()         # 进入训练模式，参数会随着迭代而改变
        result = net_do(data)              # spk_rec的格式为：[num_steps, batch_size, 类别数]
        loss_val = loss_fn(result, targets)
        optimizer.zero_grad()
        loss_val.backward(retain_graph=True)
        optimizer.step()
        loss_hist.append(loss_val.item())
        # 每25组数据输出一次
        if i % 25 == 0:
          net.eval()
          print(f"Epoch {epoch}, 第 {i} 次循环 \n训练损失: {loss_val.item():.2f}")
          acc = SF.accuracy_rate(result, targets)          # 使用峰值计数来衡量准确率
          acc_hist.append(acc)
          print(f"Accuracy: {acc * 100:.2f}%\n")
```

I also modified it according to your suggestion, but it still has no effect

```
def net_do(data):
    # utils.reset(net)
    mem_rec = []
    for i in range(num_steps):
        mem = net(data)
        mem_rec.append(mem)
    return torch.stack(mem_rec)

for epoch in range(num_epochs):
    for i, (data, targets) in enumerate(iter(train_loader)):
        utils.reset(net)
        data = data.to(device)
        targets = targets.to(device)
        net.train()         # 进入训练模式，参数会随着迭代而改变
        result = net_do(data)              # spk_rec的格式为：[num_steps, batch_size, 类别数]
        loss_val = loss_fn(result, targets)
        optimizer.zero_grad()
        loss_val.backward(retain_graph=True)
        optimizer.step()
        loss_hist.append(loss_val.item())
        # 每25组数据输出一次
        if i % 25 == 0:
          net.eval()
          print(f"Epoch {epoch}, 第 {i} 次循环 \n训练损失: {loss_val.item():.2f}")
          acc = SF.accuracy_rate(result, targets)          # 使用峰值计数来衡量准确率
          acc_hist.append(acc)
          print(f"Accuracy: {acc * 100:.2f}%\n")
```

I have been troubled by this issue for a long time, and I have encountered this issue in other tasks using snntorch, but after I added: `utils.reset(net)` After that, this problem will not occur again, but in this project, no matter how I add this line of code, it will have no effect, and will still report an error
You may be the only snntorch user I can contact. I really hope you can help me
Thank you very much 
Thank you very much
Thank you very much

**Comment by ridgerchu** [comment]
Solved by editing the reset function.
